A bit of golfing and some opinionated best practices updates 😏
OchiengEd/olm-monorepo-migration pull request #2
Opened 2024-12-26 16:31 UTC by gavinmbell

Changes that follow best practices styles.
Tried to remove code where possible to make things a bit more tidy.
Please double check that everything works in your environment smoothly.

2025-01-03 15:18 UTC, OchiengEd requested changes
Looks good. Small nit pick on typographical error.

2025-01-03 15:18 UTC, OchiengEd commented on monorepo_prep.sh
> +echo "catlogd repo: ${CATALOGD_REPO_TLD}"
Fix typographical error; Should read, `echo "catalogd repo: ..."`

2025-01-04 06:02 UTC, gavinmbell commented on monorepo_prep.sh
> +echo "catlogd repo: ${CATALOGD_REPO_TLD}"
fixed in dc8d39a1fe2816d7578efc55acfd8f4652ce04fc

2025-01-06 15:55 UTC, LalatenduMohanty approved these changes
/lgtm

2025-01-06 15:58 UTC, LalatenduMohanty commented
@OchiengEd I had accepted the invitation to have write access but still can not merge PRs. Can you please check if missed anything?

2025-01-06 16:01 UTC, OchiengEd approved these changes
/lgtm

2025-01-06 16:02 UTC, merged